### ISSUE TITLE
pianzisiquanjia

### ISSUE THREAD

**Issue by gululu3** [JisuanjiBiSheXueJie/SpringbootVuejs-Pet#1]
你好 我被一个人被开源代码骗了 结果他全家si了 她闺女还拿那钱自己花 不给他的妈妈烧纸 花圈也不买  奉劝你一句别拿别人开源的代码盈利了 家里人真si的更快

**Comment by JisuanjiBiSheXueJie** [comment]
你全家已经死完了懂吗 菜是原罪
